### ISSUE TITLE
Inventory should be able to store KV's for service as well.

### ISSUE THREAD

**Issue by eddwardo** [fieldaware/confgen#5]
For infra such as:
```
infra:
  test:
     cluster:
       - webapp
```

If user sets `confgen set /test/cluster/webapp foo bar` the value will be ignored. 
Only `confgen set /test/cluster foo bar` will be picked up.
